/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Stm32f303xx.h>
#include "Gpio.h"

GPIO_Handle_t pGPIOA_handler;



int main(void)
{
	pGPIOA_handler.pGpiox = GPIOA;
	GPIO_Clock_Control(&pGPIOA_handler, 1);
	GPIO_Clock_Control(&pGPIOA_handler, 0);
    /* Loop forever */
	//for(;;);
}
